namespace: werwer-dev
pvc:
  name: pvc-redis-service-1-jici4kixgw
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
redis:
  configmap:
    name: config-redis-service-1-jici4kixgw
  statefulset:
    name: redis-service-1-jici4kixgw
    replicas: 1
    hpa:
      name: hpa-redis-service-1-jici4kixgw
      minReplicas: 1
      maxReplicas: 1
      cpu: 70
      memory: -@memAutoScale@-
    port: 6379
    resource:
      request:
        memory: 250Mi
        cpu: 0.25
    volume:
      name: redis-service-1-jici4kixgw
  service:
    name: redis-service-1-jici4kixgw
    port: 6379
    protocol: 
  secret:
    name: secret-redis-service-1-jici4kixgw
    host: redis-service-1-jici4kixgw
    port: 6379
    password: Um9vdDEyMzQh
